a = int(input("Enter First Number: "))
b = int(input("Enter second Number: "))
c = a + b
d = a - b
e = a*b
f = a/b
print("addition of a and b is = ", c)
print("substration of a and b is = ", d)
print("multiplication of a and b is = ", e)
print("division of a and b is = ", f)
